// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as SelectExample$ReactTemplate from "./SelectExample.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(SelectExample$ReactTemplate.make, { }), "root");

export {
  
}
/*  Not a pure module */
