// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Downshift from "downshift";

function s(prim) {
  return prim;
}

function SelectExample(Props) {
  return React.createElement("div", undefined, React.createElement(Downshift.default, {
                  children: (function (param) {
                      return React.createElement("div", undefined, "KAREL");
                    })
                }));
}

var make = SelectExample;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
